openapi: 3.0.0

info:
  title: My notes documentation
  version: 0.1.9

servers:
  - url: http://127.0.0.1:5000/

paths:
  /:
    get:
      summary: Main page
      responses:
        '200':
          description: Buttons with options to log in, sign up or list the users
  /sign_up:
    post:
      summary: Sign up
      requestBody:
        required: true
        content:
          arguments:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Create a new account
  /log_in:
    post:
      summary: Log in
      requestBody:
        required: true
        content:
          arguments:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Log in successfully
  /notes/{username}:
    get:
      summary: List all notes options
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type : string
      responses:
        '200':
          description: List all notes options
  /add_notes/{username}:
    post:
      summary: Add a new note
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type : string
      requestBody:
        required: true
        content:
          arguments:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
      responses:
        '200':
          description: The note is added
  /list_notes/{username}:
    get:
      summary: List the notes
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type : string
      responses:
        '200':
          description: List all notes
  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: List all users with username and password