services:
  app:
    build: ./app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/userdb
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
