services:
  app:
    build: ./app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/userdb
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root